# Generated by Django 6.1.1 on 2026-09-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_student_bio_student_department_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
    ]
